/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1155MintableSol from "./IERC1155Mintable.sol";
export type { ierc1155MintableSol };
export type { ICurrencyManager } from "./ICurrencyManager";
